**FreedomOpMod: Remastered License**
You may copy, distribute, modify or otherwise use the FreedomOpMod: Remastered in any way shape or form.
In the event you do use the FreedomOpMod: Remastered; you may not then remove any creditation to Camzie99 or Cameron B. R. Redmore
and you may not remove or modify the Command_fopm.java.

The above license may be waived by Camzie99 / Cameron B. R. Redmore alone. No other developers may waive the license.