name: EpiclyOpMod
version: 3.0
description: My attempt at making a freedom plugin.
authors: [Camzie99, tylerhyperHD]
website: http://3p1cfreedomcraft.boards.net/
 
main: net.camtech.fopmremastered.FreedomOpModRemastered
database: false
api-version: 1.13
softdepend: [BukkitTelnet, BarAPI, CoreProtect]