name: FreedomOpModRemastered
version: 2.03
description: My attempt at making a freedom plugin.
author: Camzie99
website: http://fop.us.to

main: net.camtech.fopmremastered.FreedomOpModRemastered
database: false
depend: [CamUtils, FreedomOpModRemasteredConfigs]
softdepend: [CamVerify, BukkitTelnet, BarAPI, CoreProtect, TitleAPI, LibsDisguises]